### ISSUE TITLE
Disparu du Play Store?

### ISSUE THREAD

**Issue by awsms** [FranckRJ/RespawnIRC-Android#15]
Il semblerait que l'application ait été supprimée du store. https://play.google.com/store/apps/details?id=com.franckrj.respawnirc

**Comment by FranckRJ** [comment]
Oui, l'application est retirée du playstore à la demande de JVC. Ceux qui avaient installé l'application auront toujours les mises à jour, les autres pourront télécharger les apks via la page "release" sur github.

**Comment by FoxMcCloud45** [comment]
Mais par conséquent, sera-t-elle toujours maintenue ?
